ES_HOST = "ES_HOST"
ES_PORT = "ES_PORT"
ES_INDEX = "ES_INDEX"
# NER_URL = "NER_URL"
# PHONLP_URL = "PHONLP_URL"
BEGIN = "begin"
END = "end"
LABEL = "label"
TEXT = "text"
PRODUCT = "product"
NODE = "node"
BEGIN_INDEX = "begin_index"
END_INDEX = "end_index"

DEVICE = "DEVICE"
IP_ADDRESS = "IP_ADDRESS"
PORT = "PORT"

BPE_DIR = "BPE_DIR"
VISUAL_GROUNDING_CHECKPOINT = "VISUAL_GROUNDING_CHECKPOINT"


